default_install_hook_types:
  - pre-commit
  - commit-msg
  - post-checkout
  - post-merge
  - post-rewrite

ci:
  skip:
    - generate-config-schemas

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: detect-private-key

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.1.0
    hooks:
      - id: commitizen

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.30.0
    hooks:
      - id: check-github-workflows
      - id: check-metaschema
        files: config.sample.json

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.5.12
    hooks:
      - id: uv-sync
      - id: uv-lock # update lock file
      - id: uv-export # export lock file to requirements.txt

  - repo: local
    hooks:
      - id: generate-config-schemas
        name: Generate Config Schemas
        language: system
        entry: uv run generate-config-schema # Require venv activated
        files: '^src/check_phat_nguoi/models/'
        types: [file, python]
        verbose: true
        stages:
          - pre-commit
